spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 727423663939-nm9b6hankh9n009qhroe272qe3ujhug6.apps.googleusercontent.com
            client-secret: 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
#          facebook:
#            client-id: < Enter Facebook App ID >
#            client-secret: < Enter Facebook App Secret >
#          github:
#            client-id: < Enter Github Client ID >
#            client-secret: < Enter Github Client Secret >
#          okta:
#            client-id: < Enter Okta Client ID >
#            client-secret: < Enter Okta Client Secret >
#        provider:
#          okta:
#            authorization-uri: https://<subdomain>.okta.com/oauth2/v1/authorize
#            token-uri: https://<subdomain>.okta.com/oauth2/v1/token
#            user-info-uri: https://<subdomain>.okta.com/oauth2/v1/userinfo
#            jwk-set-uri: https://<subdomain>.okta.com/oauth2/v1/keys